version: '3'

services:
  db-mongo:
    image: mongo
    container_name: db-stocks
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"